name: mime
version: 1.0.0

description: >-
  Utilities for handling media (MIME) types, including determining a type from
  a file extension and file contents.
homepage: https://github.com/dart-lang/mime

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.16.0-nullsafety
